sonar.projectKey=7ofuuu_moodflix-v2
sonar.organization=7ofuuu
sonar.projectName=MoodFlix v2
sonar.projectVersion=0.1.0

sonar.sources=src
sonar.tests=src/__tests__
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,**/*.config.*,.next/**,coverage/**,src/**/*.d.ts
sonar.cpd.exclusions=src/__tests__/**
